apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bxs7j553c-python 
  janus-idp.io/tekton: bxs7j553c-python
  backstage.io/kubernetes-id: bxs7j553c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bxs7j553c-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  